name: Dependency Scanning for Snyk and Trivy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  snyk-scan:
    name: Snyk Dependency Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install # Adjust this to match your project's dependency manager

      - name: Install Snyk
        run: npm install -g snyk # Install Snyk CLI globally

      - name: Authenticate Snyk
        run: snyk auth "${{ secrets.SNYK_TOKEN }}"

      - name: Run Snyk to check for vulnerabilities
        run: snyk test --all-projects --severity-threshold=medium --fail-on=none > snyk-report.txt || true # Save the results and don't fail the workflow

      - name: Upload Snyk Report as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: snyk-report
          path: snyk-report.txt

      - name: Monitor project in Snyk
        run: snyk monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  trivy-scan:
    name: Trivy Filesystem Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.35.0/trivy_0.35.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.35.0_Linux-64bit.deb

      - name: Run Trivy Filesystem Scan
        run: trivy fs --exit-code 0 .
