name: Dependency and Image Scanning

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  snyk-scan:
    name: Snyk Dependency Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js (if you have Node.js dependencies)
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Snyk
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk test
        run: snyk test

      - name: Monitor project in Snyk
        run: snyk monitor

  trivy-dependency-scan:
    name: Trivy Dependency Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.35.0/trivy_0.35.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.35.0_Linux-64bit.deb

      - name: Run Trivy Filesystem Scan
        run: trivy fs --exit-code 1 --severity HIGH,CRITICAL .
        # This scans the entire repository for vulnerabilities in dependencies
        # You can add --ignore-unfixed to skip unfixed vulnerabilities
